# Generated by Django 5.1.6 on 2025-02-28 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("map", "0003_announcement_alter_result_rain_image_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sector",
            name="latitude",
        ),
        migrations.RemoveField(
            model_name="sector",
            name="longitude",
        ),
    ]
